SSPC/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^ admin/', admin.site.urls),
    url(r'^cliente/', include('apps.cliente.urls', namespace='cliente')),
    url(r'^empleado/', include('apps.empleado.urls', namespace='empleado')),
    url(r'^herramienta/', include('apps.herramienta.urls', namespace='herramienta')),
    url(r'^reporte/', include('apps.reporte.urls', namespace='reporte')),
    url(r'^servicio/', include('apps.servicio.urls', namespace='servicio')),
    url(r'^usuario/', include('apps.usuario.urls')),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,{'template_name': 'registration/password_reset_form.html', 'email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    url(r'^reset/password_reset_done',password_reset_done, {'template_name':'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},name='password_reset_complete'),
]

apps/cliente/urls.py
from django.conf.urls import url,include
from django.contrib.auth.decorators import login_required
from apps.cliente.views import index_cliente, cliente_view, cliente_list, cliente_edit, cliente_delete


urlpatterns = [
    url(r'^$', login_required(index_cliente), name='indexCliente'),
    url(r'^nuevo$', login_required(cliente_view), name='cliente_nuevo'),
    url(r'^listar$', login_required(cliente_list), name='cliente_listar'),
    url(r'^editar/(?P<id_cliente>\d+)/$', login_required(cliente_edit), name='cliente_editar'),
    url(r'^eliminar/(?P<id_cliente>\d+)/$', login_required(cliente_delete), name='cliente_eliminar'),
]

apps/empleado/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.empleado.views import index_empleado, empleado_view, empleado_list, empleado_edit, empleado_delete


urlpatterns = [
    url(r'^$',login_required(index_empleado), name='indexEmpleado'),
    url(r'^nuevo$', login_required(empleado_view), name='empleado_nuevo'),
    url(r'^listar$', login_required(empleado_list), name='empleado_listar'),
    url(r'^editar/(?P<id_empleado>\d+)/$', login_required(empleado_edit), name='empleado_editar'),
    url(r'^eliminar/(?P<id_empleado>\d+)/$', login_required(empleado_delete), name='empleado_eliminar'),

]

apps/reporte/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.reporte.views import index_reporte, reporte_view, reporte_list, reporte_edit, reporte_delete

urlpatterns = [
	url(r'^index$',login_required(index_reporte), name='index'),
	url(r'^nuevo$',login_required(reporte_view), name='reporte_nuevo'),
	url(r'^listar$', login_required(reporte_list), name='reporte_listar'),
	url(r'^editar/(?P<id_reporte>\d+)/$', login_required(reporte_edit), name='reporte_editar'),
	url(r'^eliminar/(?P<id_reporte>\d+)/$', login_required(reporte_delete), name='reporte_eliminar'),
]

apps/servicio/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.servicio.views import index_servicio, servicio_view, servicio_list, servicio_edit, servicio_delete

urlpatterns = [
    url(r'^index$',login_required(index_servicio), name='indexServicio'),
    url(r'^nuevo$',login_required(servicio_view), name='servicio_crear'),
    url(r'^listar$', login_required(servicio_list), name='servicio_listar'),
    url(r'^editar/(?P<id_servicio>\d+)/$', login_required(servicio_edit), name='servicio_editar'),
    url(r'^eliminar/(?P<id_servicio>\d+)/$', login_required(servicio_delete), name='servicio_eliminar'),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">

  {% block extrastatic %}
  {% endblock %}

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>{% block title %}Document {% endblock %}</title>
</head>
<body>
<div class="container">

  {% block navbar %}
    <div class="bs-docs-section clearfix">
        <div class="row">
            <div class="col-lg-12">
                <div class="bs-component">
                  <nav class="navbar navbar-default">
                      <div class="container-fluid">
                          <div class="navbar-header">
                            <a class="navbar-brand" href="{% url 'reporte:reporte_listar' %}">Home</a>
                          </div>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                          <ul class="nav navbar-nav">
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Cliente <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                  <li><a href="{% url 'cliente:cliente_nuevo' %}">Registrar</a></li>
                                  <li><a href="{% url 'cliente:cliente_listar' %}">Listar</a></li>
                                </ul>
                              </li>
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Empleado<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'empleado:empleado_nuevo' %}">Registrar</a></li>
                                    <li><a href="{% url 'empleado:empleado_listar' %}">Listar</a></li>
                                </ul>
                              </li>
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Herramienta<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'herramienta:herramienta_crear' %}">Registrar</a></li>
                                    <li><a href="{% url 'herramienta:herramienta_listar' %}">Listar</a></li>
                                </ul>
                              </li>
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Servicio<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'servicio:servicio_crear' %}">Registrar</a></li>
                                    <li><a href="{% url 'servicio:servicio_listar' %}">Listar</a></li>
                                </ul>
                              </li>
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Reporte<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'reporte:reporte_nuevo' %}">Registrar</a></li>
                                    <li><a href="{% url 'reporte:reporte_listar' %}">Listar</a></li>
                                </ul>
                              </li>
                          </ul>
                          <ul class="nav navbar-nav navbar-right">
                              <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'logout' %}">Salir</a></li>
                                </ul>
                              </li>
                          </ul>
                        </div>
                    </div>
                </nav>
            </div>
            </div>
        </div>
    </div>    

  {% endblock %}


  {% block content %}
  <h4>  Bloque de contenido   </h4>
  {% endblock %}


  {% block footer %}
  {% endblock%}
</div>
  <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

  {% block extrajs %}
  {% endblock %}


</body>
</html>