SSPC/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^ admin/', admin.site.urls),
    url(r'^cliente/', include('apps.cliente.urls', namespace='cliente')),
    url(r'^empleado/', include('apps.empleado.urls', namespace='empleado')),
    url(r'^herramienta/', include('apps.herramienta.urls', namespace='herramienta')),
    url(r'^reporte/', include('apps.reporte.urls', namespace='reporte')),
    url(r'^servicio/', include('apps.servicio.urls', namespace='servicio')),
    url(r'^usuario/', include('apps.usuario.urls')),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,{'template_name': 'registration/password_reset_form.html', 'email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    url(r'^reset/password_reset_done',password_reset_done, {'template_name':'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},name='password_reset_complete'),
]

apps/herramienta/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.herramienta.views import index_herramientas, herramienta_view, herramienta_list, herramienta_edit, herramienta_delete

urlpatterns = [
    url(r'^index$',login_required(index_herramientas), name='indexHerramienta'),
    url(r'^nuevo$',login_required(herramienta_view), name='herramienta_crear'),
    url(r'^listar$', login_required(herramienta_list), name='herramienta_listar'),
    url(r'^editar/(?P<id_herramienta>\d+)/$', login_required(herramienta_edit), name='herramienta_editar'),
    url(r'^eliminar/(?P<id_herramienta>\d+)/$', login_required(herramienta_delete), name='herramienta_eliminar'),
]

apps/herramienta/models.py
from django.db import models

# Create your models here.
class Herramienta(models.Model):
    nombre=models.CharField(max_length=70)
    fabricante=models.CharField(max_length=70)
    costo=models.DecimalField(max_digits=19, decimal_places=2)

    def __str__(self):
        return '{}'.format(self.nombre)

apps/herramienta/forms.py
from django import forms

from apps.herramienta.models import Herramienta


class HerramientaForm(forms.ModelForm):

	class Meta:
		model = Herramienta

		fields = [
			'nombre',
			'fabricante',
			'costo',
		]

		labels = {
			'nombre': 'Herramienta',
			'fabricante': 'Fabricante',
			'costo': 'Costo',
		}

		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'fabricante': forms.TextInput(attrs={'class':'form-control'}),
			'costo': forms.TextInput(attrs={'class':'form-control'}),
		}

apps/herramienta/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# Create your views here.

from apps.herramienta.forms import HerramientaForm
from apps.herramienta.models import Herramienta


def index_herramientas(request):
    return render(request, 'herramienta/index.html')

def herramienta_view(request):
	if request.method == 'POST':
		form=HerramientaForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('herramienta:indexHerramienta')
	else:
		form= HerramientaForm()
	return render(request, 'herramienta/herramienta_form.html', {'form': form })


def herramienta_list(request):
	herramienta = Herramienta.objects.all()
	contexto= {'herramienta': herramienta}
	return render(request, 'herramienta/herramienta_list.html', contexto)

def herramienta_edit(request, id_herramienta):
	herramienta = Herramienta.objects.get(id=id_herramienta)
	if request.method == 'GET':
		form = HerramientaForm(instance=herramienta)
	else:
		form = HerramientaForm(request.POST, instance=herramienta)
		if form.is_valid():
			form.save()
		return redirect('herramienta:herramienta_listar')
	return render(request, 'herramienta/herramienta_form.html', {'form':form})

def herramienta_delete(request, id_herramienta):
	herramienta = Herramienta.objects.get(id=id_herramienta)
	if request.method == 'POST':
		herramienta.delete()
		return redirect('herramienta:herramienta_listar')
	return render(request, 'herramienta/herramienta_delete.html', {'herramienta':herramienta})

templates/herramienta/herramienta_delete.html
{%extends 'base/base.html' %}

{% block content %}

<form method="post">
	{% csrf_token %}
	<h3>Desea eliminar el registro de {{ herramienta.nombre }}?</h3>

  <button class="btn btn-danger" type="submit">Si, eliminar</button>
  <a class="btn btn-default" href="{% url 'herramienta:herramienta_listar' %}">Cancelar</a>
</form>

{% endblock %}

templates/herramienta/herramienta_form.html
{%extends 'base/base.html' %}

{% block content %}
<h1>Registro de herramienta</h1>
<br></br>	
<form method="post">
	
  {% csrf_token %}
  {{ form.as_p }}

  <button class="btn btn-primary" type="submit">Guardar</button>
</form>

{% endblock %}

templates/herramienta/herramienta_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1 align="center">Listado de Herramientas</h1><br></br>
<table class="table table-bordered">
	<thead>
		<tr align="center">
			<td><b>id</b></td>
			<td><b>Nombre</b></td>
			<td><b>Fabricante</b></td>
			<td><b>Costo</b></td>
			<td><b>Acciones</b></td>
		</tr>

	</thead>
	<tbody>
		{% if herramienta %}
		{% for herramienta in herramienta %}
		<tr align="center">
			<td>{{ herramienta.id }}</td>
			<td>{{ herramienta.nombre }}</td>
			<td>{{ herramienta.fabricante }}</td>
			<td>$ {{ herramienta.costo }} mx</td>
			<td>
				<a class="btn btn-primary" href="{% url 'herramienta:herramienta_editar' herramienta.id %}">Editar</a>

				<a class="btn btn-danger" href="{% url 'herramienta:herramienta_eliminar' herramienta.id %}">Eliminar</a>

			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registro de herramientas</h1>

		{% endif %}
	</tbody>

</table>

{% endblock %}

templates/herramienta/index.html
{%extends 'base/base.html'%}

{% block title %}
Herramienta
{% endblock %}


{% block content %}
<h5>contenido de Herramienta</h5>
{% endblock %}