SSPC/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^ admin/', admin.site.urls),
    url(r'^cliente/', include('apps.cliente.urls', namespace='cliente')),
    url(r'^empleado/', include('apps.empleado.urls', namespace='empleado')),
    url(r'^herramienta/', include('apps.herramienta.urls', namespace='herramienta')),
    url(r'^reporte/', include('apps.reporte.urls', namespace='reporte')),
    url(r'^servicio/', include('apps.servicio.urls', namespace='servicio')),
    url(r'^usuario/', include('apps.usuario.urls')),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,{'template_name': 'registration/password_reset_form.html', 'email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    url(r'^reset/password_reset_done',password_reset_done, {'template_name':'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},name='password_reset_complete'),
]

apps/reporte/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.reporte.views import index_reporte, reporte_view, reporte_list, reporte_edit, reporte_delete

urlpatterns = [
	url(r'^index$',login_required(index_reporte), name='index'),
	url(r'^nuevo$',login_required(reporte_view), name='reporte_nuevo'),
	url(r'^listar$', login_required(reporte_list), name='reporte_listar'),
	url(r'^editar/(?P<id_reporte>\d+)/$', login_required(reporte_edit), name='reporte_editar'),
	url(r'^eliminar/(?P<id_reporte>\d+)/$', login_required(reporte_delete), name='reporte_eliminar'),
]

apps/reporte/models.py
from django.db import models
from apps.cliente.models import Cliente
from apps.empleado.models import Empleado
from apps.herramienta.models import Herramienta
from apps.servicio.models import Servicio

# Create your models here.
class Reporte(models.Model):
    fecha=models.DateField()
    descripcion=models.TextField()
    empleado=models.ForeignKey(Empleado, null=True, blank=True, on_delete=models.CASCADE)
    cliente=models.ForeignKey(Cliente, null=True, blank=True, on_delete=models.CASCADE)
    servicio=models.ManyToManyField(Servicio)
    herramienta=models.ManyToManyField(Herramienta)

apps/reporte/forms.py
from django import forms

from apps.reporte.models import Reporte


class ReporteForm(forms.ModelForm):

	class Meta:
		model= Reporte

		fields=[
			'fecha',
	    	'empleado',
	    	'cliente',
	    	'servicio',
	    	'herramienta',
	    	'descripcion',
		]

		labels={
			'fecha': "Fecha",
	    	'empleado': "Empleado",
	    	'cliente': "Cliente",
	    	'servicio': "Servicio(s) realizado(s)",
	    	'herramienta': "Herramienta(s) utilizada(s)",
	    	'descripcion': "Descripcion de servicio(s)",
		}
		widgets={
			'fecha':forms.TextInput(attrs={'class':'form-control'}),
	    	'empleado': forms.Select(attrs={'class' : 'form-control'}),
	    	'cliente': forms.Select(attrs={'class' : 'form-control'}),
	    	'servicio': forms.CheckboxSelectMultiple(),
	    	'herramienta': forms.CheckboxSelectMultiple(),
	    	'descripcion': forms.Textarea(attrs={'class':'form-control'}),
		}



			

apps/reporte/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# Create your views here.

from apps.reporte.forms import ReporteForm
from apps.reporte.models import Reporte


def index_reporte(request):
    return render(request, 'reporte/index.html')

def reporte_view(request):
	if request.method=='POST':
		form=ReporteForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('reporte:index')
	else:
		form=ReporteForm()
	return render(request,'reporte/reporte_form.html',{'form': form})


def reporte_list(request):
	reporte = Reporte.objects.all()
	contexto= {'reporte': reporte}
	return render(request, 'reporte/reporte_list.html', contexto)

def reporte_edit(request, id_reporte):
	reporte = Reporte.objects.get(id=id_reporte)
	if request.method == 'GET':
		form = ReporteForm(instance=reporte)
	else:
		form = ReporteForm(request.POST, instance=reporte)
		if form.is_valid():
			form.save()
		return redirect('reporte:reporte_listar')
	return render(request, 'reporte/reporte_form.html', {'form':form})

def reporte_delete(request, id_reporte):
	reporte = Reporte.objects.get(id=id_reporte)
	if request.method == 'POST':
		reporte.delete()
		return redirect('reporte:reporte_listar')
	return render(request, 'reporte/reporte_delete.html', {'reporte':reporte})

templates/reporte/index.html
{% extends 'base/base.html' %}

{% block title %}
Reporte
{% endblock %}


{% block content %}
<h5>contenido de Reporte</h5>
{% endblock %}

templates/reporte/reporte_delete.html
{%extends 'base/base.html' %}

{% block content %}

<form method="post">
	{% csrf_token %}
	<h3>Desea eliminar el reporte con id {{ reporte.id }}?</h3>

  <button class="btn btn-danger" type="submit">Si, eliminar</button>
  <a class="btn btn-default" href="{% url 'reporte:reporte_listar' %}">Cancelar</a>
</form>

{% endblock %}

templates/reporte/reporte_form.html
{%extends 'base/base.html' %}

{% block content %}
<h1>Registro de reporte</h1>
<br></br>	
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <button class="btn btn-primary" type="submit">Guardar</button>
</form>

{% endblock %}

templates/reporte/reporte_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1 align="center">Listado de Reportes</h1><br></br>

<table class="table table-bordered">
	<thead>
		<tr align="center">
			<td><b>id</b></td>
			<td><b>Fecha</b></td>
			<td><b>Empleado</b></td>
			<td><b>Cliente</b></td>
			<td><b>Servicio(s)</b></td>
			<td><b>Herramienta(s)</b></td>
			<td><b>Descripción de servicio(s)</b></td>
			<td><b>Acciones</b></td>
		</tr>

	</thead>
	<tbody>
		{% if reporte %}
		{% for reporte in reporte %}
		<tr align="center">
			<td>{{ reporte.id }}</td>
			<td>{{ reporte.fecha }}</td>
			<td>{{ reporte.empleado.nombre }} {{ reporte.empleado.apellido }}</td>
			<td>{{ reporte.cliente.nombre }} {{ reporte.cliente.apellido }}</td>
			<td>
			<ul>{% for servicio in reporte.servicio.all %}
				<li>
					{{servicio.nombre}}
				</li>
				{% endfor %}
			</ul>
		</td>
		<td>
			<ul>{% for herramienta in reporte.herramienta.all %}
				<li>
					{{herramienta.nombre}}
				</li>
				{% endfor %}
			</ul>
		</td>
			<td>{{ reporte.descripcion }}</td>
			<td>
				<a class="btn btn-primary" href="{% url 'reporte:reporte_editar' reporte.id %}">Editar</a>

				<a class="btn btn-danger" href="{% url 'reporte:reporte_eliminar' reporte.id %}">Eliminar</a>

			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registro de reportes</h1>

		{% endif %}
	</tbody>

</table>

{% endblock %}