SSPC/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^ admin/', admin.site.urls),
    url(r'^cliente/', include('apps.cliente.urls', namespace='cliente')),
    url(r'^empleado/', include('apps.empleado.urls', namespace='empleado')),
    url(r'^herramienta/', include('apps.herramienta.urls', namespace='herramienta')),
    url(r'^reporte/', include('apps.reporte.urls', namespace='reporte')),
    url(r'^servicio/', include('apps.servicio.urls', namespace='servicio')),
    url(r'^usuario/', include('apps.usuario.urls')),
    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),
    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset,{'template_name': 'registration/password_reset_form.html', 'email_template_name':'registration/password_reset_email.html'}, name='password_reset'),
    url(r'^reset/password_reset_done',password_reset_done, {'template_name':'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},name='password_reset_complete'),
]

apps/servicio/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.servicio.views import index_servicio, servicio_view, servicio_list, servicio_edit, servicio_delete

urlpatterns = [
    url(r'^index$',login_required(index_servicio), name='indexServicio'),
    url(r'^nuevo$',login_required(servicio_view), name='servicio_crear'),
    url(r'^listar$', login_required(servicio_list), name='servicio_listar'),
    url(r'^editar/(?P<id_servicio>\d+)/$', login_required(servicio_edit), name='servicio_editar'),
    url(r'^eliminar/(?P<id_servicio>\d+)/$', login_required(servicio_delete), name='servicio_eliminar'),
]

apps/servicio/models.py
from django.db import models

# Create your models here.
class Servicio(models.Model):
    nombre=models.CharField(max_length=100)
    descripcion=models.TextField()
    costo=models.DecimalField(max_digits=19, decimal_places=2)

    def __str__(self):
        return '{}'.format(self.nombre)

apps/servicio/forms.py
from django import forms

from apps.servicio.models import Servicio


class ServicioForm(forms.ModelForm):

	class Meta:
		model = Servicio

		fields = [
			'nombre',
			'descripcion',
			'costo',
		]

		labels = {
			'nombre': 'Servicio',
			'descripcion': 'Descripcion de servicio',
			'costo': 'Costo',
		}

		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'descripcion': forms.Textarea(attrs={'class':'form-control'}),
			'costo': forms.TextInput(attrs={'class':'form-control'}),
		}

apps/servicio/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# Create your views here.
from apps.servicio.forms import ServicioForm
from apps.servicio.models import Servicio


def index_servicio(request):
	return render(request, 'servicio/index.html')

def servicio_view(request):
	if request.method == 'POST':
		form = ServicioForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('servicio:indexServicio')
	else:
		form = ServicioForm()

	return render(request, 'servicio/servicio_form.html', {'form':form})

def servicio_list(request):
	servicio = Servicio.objects.all()
	contexto= {'servicio': servicio}
	return render(request, 'servicio/servicio_list.html', contexto)

def servicio_edit(request, id_servicio):
	servicio = Servicio.objects.get(id=id_servicio)
	if request.method == 'GET':
		form = ServicioForm(instance=servicio)
	else:
		form = ServicioForm(request.POST, instance=servicio)
		if form.is_valid():
			form.save()
		return redirect('servicio:servicio_listar')
	return render(request, 'servicio/servicio_form.html', {'form':form})

def servicio_delete(request, id_servicio):
	servicio = Servicio.objects.get(id=id_servicio)
	if request.method == 'POST':
		servicio.delete()
		return redirect('servicio:servicio_listar')
	return render(request, 'servicio/servicio_delete.html', {'servicio':servicio})

templates/servicio/index.html
{%extends 'base/base.html'%}

{% block title %}
Servicio
{% endblock %}


{% block content %}
<h5>contenido de Servicio</h5>
{% endblock %}

templates/servicio/servicio_delete.html
{%extends 'base/base.html' %}

{% block content %}

<form method="post">
	{% csrf_token %}
	<h3>Desea eliminar el registro de {{ servicio.nombre }}?</h3>

  <button class="btn btn-danger" type="submit">Si, eliminar</button>
  <a class="btn btn-default" href="{% url 'servicio:servicio_listar' %}">Cancelar</a>
</form>

{% endblock %}

templates/servicio/servicio_form.html
{%extends 'base/base.html' %}

{% block content %}
<h1>Registro de servicio</h1>
<br></br>	
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}

  <button class="btn btn-primary" type="submit">Guardar</button>
</form>

{% endblock %}

templates/servicio/servicio_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1 align="center">Listado de Servicios</h1><br></br>
<table class="table table-bordered">
	<thead>
		<tr align="center">
			<td><b>id</b></td>
			<td><b>Nombre</b></td>
			<td><b>Descripción</b></td>
			<td><b>Costo</b></td>
			<td><b>Acciones</b></td>
		</tr>

	</thead>
	<tbody>
		{% if servicio %}
		{% for servicio in servicio %}
		<tr align="center">
			<td>{{ servicio.id }}</td>
			<td>{{ servicio.nombre }}</td>
			<td>{{ servicio.descripcion }}</td>
			<td>${{ servicio.costo }} mx</td>
			<td>
				<a class="btn btn-primary" href="{% url 'servicio:servicio_editar' servicio.id %}">Editar</a>

				<a class="btn btn-danger" href="{% url 'servicio:servicio_eliminar' servicio.id %}">Eliminar</a>

			</td>
		</tr>
		{% endfor %}

		{% else %}
		<h1>No hay registro de servicios</h1>

		{% endif %}
	</tbody>

</table>

{% endblock %}